### ISSUE TITLE
utf-8 support

### ISSUE THREAD

**Issue by wasabiz** [picrin-scheme/benz#5]

**Comment by KeenS** [comment]
@wasabiz I have a question. When it comes that benz (picrin) supports UTF-8, what value would `pic_char` contain? UTF-8 value, or Unicode code point?

**Comment by wasabiz** [comment]
@KeenS 

I believe code point is better. I gave it some tries so far but not completed yet. There are too many changes required to go ahead the UTF-8 support.

**Comment by wasabiz** [comment]
Please continue the discussion of this topic from now at picrin's thread
